version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
     - mongo
  redis:
    image: redis

    volumes:
     - /data/redis:/data

    command: ["redis-server", "--appendonly", "yes"]

  mongo:
    image: mongo

    volumes:
     - /data/mongo:/data/db
